limit_req_zone $binary_remote_addr zone=prowlarr_limit:10m rate=2r/s;

server {
    listen 9697;
    location / {
        limit_req zone=prowlarr_limit burst=5 nodelay;
        proxy_pass http://prowlarr:9696\;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
